### ISSUE TITLE
URL con ancora verso documentazione: comportamento strano

### ISSUE THREAD

**Issue by aborruso** [ondata/confini-amministrativi-istat#27]
Caro @jenkin,
se creo un hyperlink così

```
[doc](https://confini-amministrativi.it/#docs)
```

che renderizzo qui con [doc](https://confini-amministrativi.it/#docs), si apre il browser e l'URL viene cambiato in `https://confini-amministrativi.it/#/docs` e non funziona correttamente.

**Comment by jenkin** [comment]
Ho indagato, colpa di Swagger UI, inserirò questa fix in una prossima PR.

**Comment by jenkin** [comment]
Occhio che sono cambiate le ancora, ora sono `#/map` e `#/docs`.
