### ISSUE TITLE
URL immediati

### ISSUE THREAD

**Issue by pigreco** [ondata/confini-amministrativi-istat#28]
Per utilizzare velocemente i dati in QGIS:

1. https://confini-amministrativi.it/api/v2/it/20230101/unita-territoriali-sovracomunali.zip
2. https://confini-amministrativi.it/api/v2/it/20240101/regioni.zip
3. https://confini-amministrativi.it/api/v2/it/20240101/ripartizioni-geografiche.zip
4. https://confini-amministrativi.it/api/v2/it/20240101/comuni.zip

![image](https://github.com/ondata/confini-amministrativi-istat/assets/7631137/85403fee-2b82-4985-b133-2aedd01bec6a)

**Comment by jenkin** [comment]
Suggerisci di inserire questo piccolo tutorial nella documentazione?

**Comment by pigreco** [comment]
> Suggerisci di inserire questo piccolo tutorial nella documentazione?

nella documentazione sarebbe utile avere una sezione con dei URL immediati, quindi suggerirei di mettere quell'elenco.

**Comment by pigreco** [comment]
@jenkin i link non funzionano più

**Comment by jenkin** [comment]
@pigreco In http dovrebbero funzionare, in https stiamo sistemando.

**Comment by jenkin** [comment]
@pigreco Dovrebbe essersi risolto tutto, confermi?

**Comment by pigreco** [comment]
> confermi?

yep!

**Comment by jenkin** [comment]
@pigreco Ho aggiunto una sezione [Tutorial](https://github.com/ondata/confini-amministrativi-istat?tab=readme-ov-file#tutorial) e il primo è [proprio il tuo](https://github.com/ondata/confini-amministrativi-istat/blob/main/tutorials/qgis/README.md)! :D Se vuoi ampliarlo, apri pure una PR... grazie!
