### ISSUE TITLE
Docker build non funziona

### ISSUE THREAD

**Issue by ghirardinicola** [ondata/confini-amministrativi-istat#4]
executor failed running [/bin/sh -c cd /tmp/libspatialite-5.0.0-beta0 &&     ./configure --enable-rttopo=yes --enable-gcp=yes &&     make -j8 &&     make install-strip]: exit code: 1

Sto girando docker su mac intel, spero non conti..

**Comment by ghirardinicola** [comment]
Ho semplificato il dockerfile installando da apt spatialite. Se vi piace possiamo mergiare
https://github.com/ghirardinicola/confini-amministrativi-istat/commit/3243b560178d5004bb5a23c69a7fd610a9414621

**Comment by ghirardinicola** [comment]
Cambiato anche il readme accordingly
https://github.com/ghirardinicola/confini-amministrativi-istat/commit/982d6ed829128d93184d70c76e1cefaba4ea70f3

**Comment by jenkin** [comment]
Grazie!
