### ISSUE TITLE
Il browser blocca il download

### ISSUE THREAD

**Issue by aborruso** [ondata/confini-amministrativi-istat#9]
Ho scaricato il file zip delle regioni e il browser blocca il download, riportandomi a [questa guida](https://support.google.com/chrome/answer/6261569?visit_id=638427662713832996-4240192527&p=ib_download_blocked&hl=en&rd=1).

Succede soltanto a me?

![image](https://github.com/ondata/confini-amministrativi-istat/assets/30607/390498b9-7e9f-42fe-a524-0e94891eb7f3)

![image](https://github.com/ondata/confini-amministrativi-istat/assets/30607/45f396ad-3250-44d8-8539-b273f0cd35b4)

**Comment by aborruso** [comment]
@lorenzoperone a te su chrome succede?

Se no, chiudo

**Comment by lorenzoperone** [comment]
Confermo funzionamento su Google Chrome su Mac
